# Generated by Django 6.1.1 on 2026-10-07 14:48

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_username_polish_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Użytkownik o takiej nazwie już istnieje.'}, max_length=150, unique=True, validators=[accounts.validators.UsernameValidator()]),
        ),
    ]
