# Generated by Django 6.1.1 on 2026-10-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_username_allow_spaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_reminded_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
