# Generated by Django 6.1.1 on 2026-10-08 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('condition', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('awaiting_result', 'Awaiting Result'), ('resolved', 'Resolved'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('void', 'Void')], default='proposed', max_length=16)),
                ('outcome', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PactParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('opponent', 'Opponent')], default='opponent', max_length=8)),
                ('side', models.CharField(blank=True, max_length=32)),
                ('stake_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('stake_note', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(choices=[('invited', 'Invited'), ('requested', 'Requested'), ('active', 'Active'), ('settled', 'Settled'), ('void', 'Void'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='invited', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pacts.pact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pact_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OutcomeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('superseded', 'Superseded')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(null=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='pacts.pact')),
                ('wager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='pacts.pactparticipant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='pact',
            index=models.Index(fields=['status', '-created_at'], name='pacts_pact_status_d44572_idx'),
        ),
        migrations.AddConstraint(
            model_name='pactparticipant',
            constraint=models.UniqueConstraint(fields=('pact', 'user'), name='pact_participant_unique'),
        ),
        migrations.AddConstraint(
            model_name='pactparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'host')), fields=('pact',), name='pact_single_host'),
        ),
    ]
