# Generated by Django 6.1.1 on 2026-10-09 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacts', '0001_initial'),
        ('voting', '0003_poll_previous_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomeproposal',
            name='ruling_poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voting.poll'),
        ),
        migrations.AddField(
            model_name='outcomeproposal',
            name='verdicts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pact',
            name='last_nudged_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='outcomeproposal',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('disputed', 'Disputed'), ('superseded', 'Superseded'), ('overruled', 'Overruled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='outcomeproposal',
            name='wager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='pacts.pactparticipant'),
        ),
        migrations.AlterField(
            model_name='pactparticipant',
            name='state',
            field=models.CharField(choices=[('invited', 'Invited'), ('requested', 'Requested'), ('active', 'Active'), ('settled', 'Settled'), ('void', 'Void'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='invited', max_length=10),
        ),
        migrations.CreateModel(
            name='JoinConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='pacts.pactparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'approver'), name='pact_join_consent_unique')],
            },
        ),
        migrations.CreateModel(
            name='OutcomeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='pacts.outcomeproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proposal', 'user'), name='pact_confirmation_unique')],
            },
        ),
    ]
