# Generated by Django 6.1.1 on 2026-10-09 00:41

import django.db.models.deletion
from django.db import migrations, models


def predictions_become_group_bets(apps, schema_editor):
    """A prediction is a group bet without stakes, so the kind is folded into `group_bet`."""
    apps.get_model("pacts", "Pact").objects.filter(kind="prediction").update(kind="group_bet")


class Migration(migrations.Migration):

    dependencies = [
        ('pacts', '0003_attachments'),
        ('voting', '0003_poll_previous_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pact',
            name='is_open',
        ),
        migrations.AddField(
            model_name='pact',
            name='judgment_poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voting.poll'),
        ),
        migrations.RunPython(predictions_become_group_bets, migrations.RunPython.noop),
    ]
