# Generated by Django 6.1.1 on 2026-10-01 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('close_reason', models.CharField(choices=[('auto', 'Auto'), ('creator', 'Creator')], max_length=8, null=True)),
                ('result', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.JSONField(null=True)),
                ('vetoed', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='voting.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['status', '-created_at'], name='voting_poll_status_b22b22_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollparticipant',
            constraint=models.UniqueConstraint(fields=('poll', 'user'), name='unique_participant'),
        ),
    ]
