# Generated by Django 6.1.1 on 2026-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='proposed_avatar',
            field=models.ImageField(blank=True, upload_to='poll_proposals/'),
        ),
        migrations.AddField(
            model_name='poll',
            name='reminders_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='close_reason',
            field=models.CharField(choices=[('auto', 'Auto'), ('creator', 'Creator'), ('expired', 'Expired')], max_length=8, null=True),
        ),
    ]
