# Generated by Django 6.1.1 on 2026-10-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_deadlines_and_profile_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='previous_avatar',
            field=models.ImageField(blank=True, upload_to='poll_proposals/'),
        ),
    ]
