# Generated by Django 6.1.1 on 2026-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_drop_paid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='item',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='currency',
            field=models.CharField(blank=True, default='PLN', max_length=3),
        ),
    ]
