# Generated by Django 6.1.1 on 2026-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_entry_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='category',
            field=models.CharField(blank=True, choices=[('lodging', 'Zakwaterowanie'), ('bills', 'Opłaty'), ('groceries', 'Zakupy spożywcze'), ('fun', 'Rozrywka'), ('health', 'Opieka zdrowotna'), ('insurance', 'Ubezpieczenie'), ('transport', 'Transport'), ('food', 'Restauracje i bary'), ('shopping', 'Shopping'), ('weed', 'Zioło'), ('other', 'Inne')], max_length=16),
        ),
    ]
