# Generated by Django 6.1.1 on 2026-10-01 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SantaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=8)),
                ('deadline', models.DateTimeField()),
                ('gift_tiers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SantaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(blank=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='santa_assignments', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='secretsanta.santaevent')),
            ],
        ),
        migrations.CreateModel(
            name='SantaGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='secretsanta.santaassignment')),
            ],
            options={
                'ordering': ('-amount',),
            },
        ),
        migrations.AddConstraint(
            model_name='santaevent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='single_active_santa_event'),
        ),
        migrations.AddConstraint(
            model_name='santaassignment',
            constraint=models.UniqueConstraint(fields=('event', 'giver'), name='unique_santa_giver'),
        ),
        migrations.AddConstraint(
            model_name='santagift',
            constraint=models.UniqueConstraint(fields=('assignment', 'amount'), name='unique_santa_gift'),
        ),
    ]
