# Generated by Django 6.1.1 on 2026-10-02 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='santaassignment',
            name='unique_santa_giver',
        ),
        migrations.AddField(
            model_name='santaassignment',
            name='tier_index',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='santaevent',
            name='mode',
            field=models.CharField(choices=[('single', 'Single'), ('per_tier', 'Per Tier')], default='single', max_length=8),
        ),
        migrations.AddConstraint(
            model_name='santaassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('tier_index__isnull', True)), fields=('event', 'giver'), name='unique_santa_giver'),
        ),
        migrations.AddConstraint(
            model_name='santaassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('tier_index__isnull', False)), fields=('event', 'giver', 'tier_index'), name='unique_santa_giver_tier'),
        ),
    ]
