# Generated by Django 6.1.2 on 2026-10-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0002_gift_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SantaHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_index', models.PositiveSmallIntegerField(null=True)),
                ('ideas', models.JSONField(default=list)),
                ('asked_at', models.DateTimeField()),
                ('answered_at', models.DateTimeField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='secretsanta.santaevent')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('tier_index__isnull', True)), fields=('event', 'receiver'), name='unique_santa_help'), models.UniqueConstraint(condition=models.Q(('tier_index__isnull', False)), fields=('event', 'receiver', 'tier_index'), name='unique_santa_help_tier')],
            },
        ),
    ]
